[package]
name = "particle_life_rust"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_egui = "0.33.0"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[lib]
crate-type = ["cdylib", "rlib"]